apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - headlamp.yaml
  - metrics-server.yaml
  - nginx.yaml
  - cilium.yaml
  - longhorn.yaml
  - kube-prometheus.yaml