apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer
spec:
  acme:
    # Use Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@drogon.tech     # your email for LE registration
    privateKeySecretRef:
      name: cloudflare-issuer-key      # will store your ACME private key
    solvers:
      - dns01:
          cloudflare:
            email: admin@drogon.tech
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token