apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ciliumconfig
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/networking/cilium/config
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: infrastructure

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system