apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - 1-sources.yaml
  - 2-ciliumhelm.yaml
  - 3-infrastructure.yaml
  - 4-ciliumconfig.yaml
  - 5-certconfig.yaml
  - 6-monitoring.yaml
  - 7-apps.yaml
